version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 950622314338.dkr.ecr.us-east-1.amazonaws.com 

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t ecs:latest .
      - docker tag ecs:latest public.ecr.aws/d3f1q5y4/ecs:latest      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push public.ecr.aws/d3f1q5y4/ecs:latest